# .github/workflows/deploy.yml

name: Deploy Static Website to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf /tmp/site
            mkdir -p /tmp/site
            echo "${{ github.event.head_commit.message }}" > /tmp/site/version.txt
            sudo rm -rf /var/www/html/*
            sudo cp -r * /var/www/html/
