name: Deploy to EC2

on:
  push:
    branches: [main]  # Change if you're using another branch

jobs:
  deploy:
    runs-on: ec2-user

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo -e "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2 via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/Static-site-devops-project  # Change to your folder on EC2
          git pull origin main
        EOF
