name: Deploy to EC2

on:
  push:
    branches: 
      - main  # Change if you're using another branch
      - dev

jobs:
  deploy:
    runs-on:  ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo -e "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2 via SSH
      run: |
       ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
       if [ ! -d ~/yourrepo/.git ]; then
       rm -rf ~/yourrepo
       git clone https://github.com/Varun-syd/Static-site-devops-project.git ~/yourrepo
       fi
       bash ~/pull-latest.sh "${{ github.ref_name }}"
       EOF
